# Generated by Django 5.2.4 on 2025-09-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_attendance_options_attendance_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
    ]
